### ISSUE TITLE
YII migrate fails as vendor is not there

### ISSUE THREAD

**Issue by Cruiser13** [kartik-v/yii2-app-practical-a#1]
If you follow the setup you'll most likely get an error when using YII migrate command:
Warning: require(xy\yii2\app/vendor/autoload.php): failed
to open stream: No such file or directory in xy\yii2\app\yii on line 18

Fatal error: require(): Failed opening required 'Fxy\yii2\app/vendor/autoload.php' (include_path='.;C:\php\pear') in xy\yii2\app\yii on line 18

Solution is to copy vendor directory from original yii2 advanced template.

**Comment by vanbumi** [comment]
I can not find the page for those vendor https://github.com/yiisoft/yii2/releases/download/2.0.0-beta/yii-advanced-app-2.0.0-beta.tg, page error 404

**Comment by vanbumi** [comment]
also the vendor : https://github.com/yiisoft/yii2/tree/master/apps/advanced/vendor

**Comment by vlad-ovsyannikov** [comment]
https://github.com/yiisoft/yii2/tree/master/apps/advanced/vendor - link is broken
