### ISSUE TITLE
Blank screen when install

### ISSUE THREAD

**Issue by juanla** [kartik-v/yii2-app-practical-a#21]
Hi, I installed this template today for first time. I found a problem when I tried load the main web for first time:
The file or directory to be published does not exist: /home.../htdocs/vendor/bower/jquery/dist

Well, I noticed that my vendor folder have next structure:
vendor\bower\bower-asset\jquery\dist

This adds bowe-asset folder inside, and provoque the problem. If any member of  project can fix it.

**Comment by kartik-v** [comment]
Done via v1.5.1
